In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/food_coded.csv')

In [ ]:
df

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [ ]:
df.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe

<bound method NDFrame.describe of        GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0      2.4       2          1               430           NaN           315.0
1    3.654       1          1               610           3.0           420.0
2      3.3       1          1               720           4.0           420.0
3      3.2       1          1               430           3.0           420.0
4      3.5       1          1               720           2.0           420.0
..     ...     ...        ...               ...           ...             ...
120    3.5       1          1               610           4.0           420.0
121      3       1          1               265           2.0           315.0
122  3.882       1          1               720           NaN           420.0
123      3       2          1               720           4.0           420.0
124    3.9       1          1               430           NaN           315.0

     coffee                             comfort_food  \
0         1                                     none
1         2              chocolate, chips, ice cream
2         2          frozen yogurt, pizza, fast food
3         2         Pizza, Mac and cheese, ice cream
4         2             Ice cream, chocolate, chips
..      ...                                      ...
120       2  wine. mac and cheese, pizza, ice cream
121       2               Pizza / Wings / Cheesecake
122       1               rice, potato, seaweed soup
123       1             Mac n Cheese, Lasagna, Pizza
124       2             Chocolates, pizza, and Ritz.

                              comfort_food_reasons  \
0                            we dont have comfort
1                             Stress, bored, anger
2                                  stress, sadness
3                                          Boredom
4                       Stress, boredom, cravings
..                                             ...
120                           boredom and sadness
121                Loneliness / Homesick / Sadness
122                                        sadness
123  happiness, they are some of my favorite foods
124               hormones, Premenstrual syndrome.

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1
1                           1.0  ...   1.0     1.0          2
2                           1.0  ...   1.0     2.0          5
3                           2.0  ...   1.0     2.0          5
4                           1.0  ...   1.0     1.0          4
..                          ...  ...   ...     ...        ...
120                         NaN  ...   1.0     1.0          5
121                         NaN  ...   1.0     NaN          4
122                         NaN  ...   1.0     2.0          5
123                         NaN  ...   2.0     2.0          1
124                         NaN  ...   1.0     2.0          2

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1
1               725.0              690  Basketball            4         2
2              1165.0              500         none           5         1
3               725.0              690          NaN           3         1
4               940.0              500     Softball           4         2
..                ...              ...          ...         ...       ...
120             940.0              500     Softball           5         1
121             940.0              500  basketball            5         2
122             580.0              690         none           4         2
123             940.0              500          NaN           3         1
124             725.0              345          NaN           4         2

     waffle_calories                    weight
0               1315                       187
1                900                       155
2                900  I'm not answering this.
3               1315             Not sure, 240
4                760                       190
..               ...                       ...
120             1315                       156
121             1315                       180
122             1315                       120
123             1315                       135
124              575                       135

[125 rows x 61 columns]>

In [ ]:
numeric_columns = []
for column in df.columns:
    if pd.api.types.is_numeric_dtype(df[column]):
        numeric_columns.append(column)
numeric_columns

['Gender',
 'breakfast',
 'calories_chicken',
 'calories_day',
 'calories_scone',
 'coffee',
 'comfort_food_reasons_coded',
 'cook',
 'comfort_food_reasons_coded.1',
 'cuisine',
 'diet_current_coded',
 'drink',
 'eating_changes_coded',
 'eating_changes_coded1',
 'eating_out',
 'employment',
 'ethnic_food',
 'exercise',
 'father_education',
 'fav_cuisine_coded',
 'fav_food',
 'fries',
 'fruit_day',
 'grade_level',
 'greek_food',
 'healthy_feeling',
 'ideal_diet_coded',
 'income',
 'indian_food',
 'italian_food',
 'life_rewarding',
 'marital_status',
 'mother_education',
 'nutritional_check',
 'on_off_campus',
 'parents_cook',
 'pay_meal_out',
 'persian_food',
 'self_perception_weight',
 'soup',
 'sports',
 'thai_food',
 'tortilla_calories',
 'turkey_calories',
 'veggies_day',
 'vitamins',
 'waffle_calories']

In [ ]:
numeric_columns = df.select_dtypes(include=['number']).columns


for column in numeric_columns:

    column_mean = df[column].mean()

    df[column].fillna(column_mean)

df

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [ ]:
df['type_sports'].unique()
df['weight'].unique()

array(['187', '155', "I'm not answering this. ", 'Not sure, 240', '190',
       '180', '137', '125', '116', '110', '264', '123', '185', '145',
       '170', '135', '165', '175', '195', '105', '160', '167', '115',
       '205', nan, '128', '150', '140', '120', '100', '113', '168', '169',
       '200', '265', '192', '118', '210', '112', '144 lbs', '130', '127',
       '129', '260', '184', '230', '138', '156'], dtype=object)

In [ ]:
df['type_sports'].value_counts()

type_sports
none                        8
Hockey                      7
Soccer                      4
softball                    4
soccer                      3
                           ..
I used to play softball     1
 None                       1
Tennis, Basketball          1
No, I don't play sport.     1
basketball                  1
Name: count, Length: 66, dtype: int64

In [ ]:
object_columns = df.select_dtypes(include=['object']).columns
df[object_columns]

,GPA,comfort_food,comfort_food_reasons,diet_current,eating_changes,father_profession,fav_cuisine,food_childhood,healthy_meal,ideal_diet,meals_dinner_friend,mother_profession,type_sports,weight
0,2.4,none,we dont have comfort,eat good and exercise,eat faster,profesor,Arabic cuisine,rice and chicken,looks not oily,being healthy,"rice, chicken, soup",unemployed,car racing,187
1,3.654,"chocolate, chips, ice cream","Stress, bored, anger",I eat about three times a day with some snacks...,I eat out more than usual.,Self employed,Italian,"chicken and biscuits, beef soup, baked beans","Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,"Pasta, steak, chicken",Nurse RN,Basketball,155
2,3.3,"frozen yogurt, pizza, fast food","stress, sadness","toast and fruit for breakfast, salad for lunch...",sometimes choosing to eat fast food instead of...,owns business,italian,"mac and cheese, pizza, tacos",usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet,"chicken and rice with veggies, pasta, some kin...",owns business,none,I'm not answering this.
3,3.2,"Pizza, Mac and cheese, ice cream",Boredom,"College diet, cheap and easy foods most nights...",Accepting cheap and premade/store bought foods,Mechanic,Turkish,"Beef stroganoff, tacos, pizza","Fresh fruits& vegetables, organic meats","Healthy, fresh veggies/fruits & organic foods",Grilled chicken \rStuffed Shells\rHomemade Chili,Special Education Teacher,NaN,"Not sure, 240"
4,3.5,"Ice cream, chocolate, chips","Stress, boredom, cravings",I try to eat healthy but often struggle becaus...,I have eaten generally the same foods but I do...,IT,Italian,"Pasta, chicken tender, pizza","A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",Substance Abuse Conselor,Softball,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,"wine. mac and cheese, pizza, ice cream",boredom and sadness,"My diet consists mainly of coffee, water, frui...",I have noticed there is less time for a prepar...,Accountant,Italian,Stromboli Mac and Cheese and Pizza,mainly protein and vegetables with a complex c...,My ideal diet would consist of a majority of w...,"pasta, fish, steak",Radiological Technician,Softball,156
121,3,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,A college student with an imbalanced diet tryi...,Eating Pizza as an excuse when there is nothin...,Doctor,Mexican Food,"Isombe , Plantains and Ugali","A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...,Fried Rice \rBaked potatoes \rCurry Chicken,Public Health Advisor,basketball,180
122,3.882,"rice, potato, seaweed soup",sadness,"Rice, oatmeal, and tea",less rice,CEO of company,Korean,Rice and potato,lots of vegetables,lots of veggies,"meat, rice, kimchi",Real Estate manageer,none,120
123,3,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",I try to eat as healthy as possible everyday. ...,I don't eat as much on a daily basis since com...,Store manager at Giant Eagle,Italian,pizza and spaghetti,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...,"Pizza, Spaghetti, Baked Ziti",Receptionist for a medical supply company,NaN,135
124,3.9,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",high in protein and low in carbohydrates.,I have learned to eat more vegetables.,Journalist,HISPANIC CUISINE.,"rice, beans, and chicken / pizza/ tenders","a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...","Vegetables, Meat, and rice.",House-wife,NaN,135

In [ ]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35',
       'Personal ', '2.6', '3.67', '3.73', '3.79 bitch', '2.71', '3.68',
       '3.75', '3.92', 'Unknown', '3.77', '3.63', '3.882'], dtype=object)

In [ ]:

df['GPA'] = pd.to_numeric(df['GPA'], errors='coerce')
mean_GPA = df['GPA'].mean()
df['GPA'].fillna(mean_GPA)
df['GPA'].unique()

array([2.4  , 3.654, 3.3  , 3.2  , 3.5  , 2.25 , 3.8  , 3.904, 3.4  ,
       3.6  , 3.1  ,   nan, 4.   , 2.2  , 3.87 , 3.7  , 3.9  , 2.8  ,
       3.   , 3.65 , 3.89 , 2.9  , 3.605, 3.83 , 3.292, 3.35 , 2.6  ,
       3.67 , 3.73 , 2.71 , 3.68 , 3.75 , 3.92 , 3.77 , 3.63 , 3.882])

In [ ]:
df['weight'].unique()

array(['187', '155', "I'm not answering this. ", 'Not sure, 240', '190',
       '180', '137', '125', '116', '110', '264', '123', '185', '145',
       '170', '135', '165', '175', '195', '105', '160', '167', '115',
       '205', nan, '128', '150', '140', '120', '100', '113', '168', '169',
       '200', '265', '192', '118', '210', '112', '144 lbs', '130', '127',
       '129', '260', '184', '230', '138', '156'], dtype=object)

In [ ]:
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')
mean_weight = df['weight'].mean()
df['weight'].fillna(mean_weight)
print(df['weight'].unique())

[187. 155.  nan 190. 180. 137. 125. 116. 110. 264. 123. 185. 145. 170.
 135. 165. 175. 195. 105. 160. 167. 115. 205. 128. 150. 140. 120. 100.
 113. 168. 169. 200. 265. 192. 118. 210. 112. 130. 127. 129. 260. 184.
 230. 138. 156.]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           120 non-null    float64
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        120 non-null    float64
dtypes: float64(22), int64(27), object(12)
memory usage: 59.7+ KB

In [ ]:
object_columns = df.select_dtypes(include=['object']).columns
df[object_columns]

,comfort_food,comfort_food_reasons,diet_current,eating_changes,father_profession,fav_cuisine,food_childhood,healthy_meal,ideal_diet,meals_dinner_friend,mother_profession,type_sports
0,none,we dont have comfort,eat good and exercise,eat faster,profesor,Arabic cuisine,rice and chicken,looks not oily,being healthy,"rice, chicken, soup",unemployed,car racing
1,"chocolate, chips, ice cream","Stress, bored, anger",I eat about three times a day with some snacks...,I eat out more than usual.,Self employed,Italian,"chicken and biscuits, beef soup, baked beans","Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,"Pasta, steak, chicken",Nurse RN,Basketball
2,"frozen yogurt, pizza, fast food","stress, sadness","toast and fruit for breakfast, salad for lunch...",sometimes choosing to eat fast food instead of...,owns business,italian,"mac and cheese, pizza, tacos",usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet,"chicken and rice with veggies, pasta, some kin...",owns business,none
3,"Pizza, Mac and cheese, ice cream",Boredom,"College diet, cheap and easy foods most nights...",Accepting cheap and premade/store bought foods,Mechanic,Turkish,"Beef stroganoff, tacos, pizza","Fresh fruits& vegetables, organic meats","Healthy, fresh veggies/fruits & organic foods",Grilled chicken \rStuffed Shells\rHomemade Chili,Special Education Teacher,NaN
4,"Ice cream, chocolate, chips","Stress, boredom, cravings",I try to eat healthy but often struggle becaus...,I have eaten generally the same foods but I do...,IT,Italian,"Pasta, chicken tender, pizza","A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",Substance Abuse Conselor,Softball
...,...,...,...,...,...,...,...,...,...,...,...,...
120,"wine. mac and cheese, pizza, ice cream",boredom and sadness,"My diet consists mainly of coffee, water, frui...",I have noticed there is less time for a prepar...,Accountant,Italian,Stromboli Mac and Cheese and Pizza,mainly protein and vegetables with a complex c...,My ideal diet would consist of a majority of w...,"pasta, fish, steak",Radiological Technician,Softball
121,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,A college student with an imbalanced diet tryi...,Eating Pizza as an excuse when there is nothin...,Doctor,Mexican Food,"Isombe , Plantains and Ugali","A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...,Fried Rice \rBaked potatoes \rCurry Chicken,Public Health Advisor,basketball
122,"rice, potato, seaweed soup",sadness,"Rice, oatmeal, and tea",less rice,CEO of company,Korean,Rice and potato,lots of vegetables,lots of veggies,"meat, rice, kimchi",Real Estate manageer,none
123,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",I try to eat as healthy as possible everyday. ...,I don't eat as much on a daily basis since com...,Store manager at Giant Eagle,Italian,pizza and spaghetti,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...,"Pizza, Spaghetti, Baked Ziti",Receptionist for a medical supply company,NaN
124,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",high in protein and low in carbohydrates.,I have learned to eat more vegetables.,Journalist,HISPANIC CUISINE.,"rice, beans, and chicken / pizza/ tenders","a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...","Vegetables, Meat, and rice.",House-wife,NaN

In [ ]:
object_columns = df.select_dtypes(include=['object']).columns
for column in object_columns:
    unique_values_count = df[column].nunique()
    print(f"Column '{column}' has {unique_values_count} unique values.")

Column 'comfort_food' has 124 unique values.
Column 'comfort_food_reasons' has 106 unique values.
Column 'diet_current' has 124 unique values.
Column 'eating_changes' has 121 unique values.
Column 'father_profession' has 114 unique values.
Column 'fav_cuisine' has 60 unique values.
Column 'food_childhood' has 114 unique values.
Column 'healthy_meal' has 124 unique values.
Column 'ideal_diet' has 124 unique values.
Column 'meals_dinner_friend' has 121 unique values.
Column 'mother_profession' has 112 unique values.
Column 'type_sports' has 66 unique values.

In [ ]:
object_columns = df.select_dtypes(include=['object']).columns


for column in object_columns:
    print(f"Value counts for column '{column}':")
    print(df[column].value_counts().sort_values(ascending=False))
    print()

Value counts for column 'comfort_food':
comfort_food
none                                       1
chocolate, chips, ice cream                1
frozen yogurt, pizza, fast food            1
Pizza, Mac and cheese, ice cream           1
Ice cream, chocolate, chips                1
                                          ..
wine. mac and cheese, pizza, ice cream     1
Pizza / Wings / Cheesecake                 1
rice, potato, seaweed soup                 1
Mac n Cheese, Lasagna, Pizza               1
Chocolates, pizza, and Ritz.               1
Name: count, Length: 124, dtype: int64

Value counts for column 'comfort_food_reasons':
comfort_food_reasons
boredom                                          7
Boredom                                          3
Boredom                                          3
sadness                                          3
Stress and boredom                               2
                                                ..
Happiness, boredom, social event                 1
boredom and sadness                              1
Loneliness / Homesick / Sadness                  1
happiness, they are some of my favorite foods    1
hormones, Premenstrual syndrome.                 1
Name: count, Length: 106, dtype: int64

Value counts for column 'diet_current':
diet_current
eat good and exercise                                                                                                                                                        1
I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan              1
toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner                                                           1
College diet, cheap and easy foods most nights. Weekends traditionally, cook better homemade meals                                                                           1
I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats.     1
                                                                                                                                                                            ..
My diet consists mainly of coffee, water, fruits, vegetables, and chicken. I tend to stay away from bread and pasta as much as possible.                                     1
A college student with an imbalanced diet trying to be healthy.                                                                                                              1
Rice, oatmeal, and tea                                                                                                                                                       1
I try to eat as healthy as possible everyday.  I have fruit, yogurt and a protein shake everyday.  The other foods i eat vary on a day to day basis.                         1
high in protein and low in carbohydrates.                                                                                                                                    1
Name: count, Length: 124, dtype: int64

Value counts for column 'eating_changes':
eating_changes
none                                                                                                                                                    2
I eat out more than usual.                                                                                                                              1
sometimes choosing to eat fast food instead of cooking simply for convenience                                                                           1
Accepting cheap and premade/store bought foods                                                                                                          1
I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker.     1
                                                                                                                                                       ..
I have noticed there is less time for a prepared meal, so quick and easy has become the norm.                                                           1
Eating Pizza as an excuse when there is nothing else to it.                                                                                             1
less rice                                                                                                                                               1
I don't eat as much on a daily basis since coming to college.                                                                                           1
I have learned to eat more vegetables.                                                                                                                  1
Name: count, Length: 121, dtype: int64

Value counts for column 'father_profession':
father_profession
business owner                  2
IT                              2
Construction                    2
Dentist                         2
Lawyer                          2
                               ..
Accountant                      1
Doctor                          1
CEO of company                  1
Store manager at Giant Eagle    1
Journalist                      1
Name: count, Length: 114, dtype: int64

Value counts for column 'fav_cuisine':
fav_cuisine
Italian                                     22
Italian                                     19
italian                                      6
Mexican                                      5
Mexican                                      4
Chinese                                      3
American                                     3
American                                     3
Asian                                        2
Chinese                                      2
Thai                                         2
italian                                      2
Indian                                       2
Korean                                       2
italian food                                 1
Anything american style.                     1
African                                      1
Orange chicken and chow mani noodles         1
Seafood                                      1
Chicken                                      1
American or Italian                          1
don't have one                               1
Italian food                                 1
Italian/German                               1
Indian food - samosas are amazing            1
Turkish                                      1
Jamaican                                     1
Arabic cuisine                               1
French                                       1
Spanish                                      1
mexican                                      1
chinese                                      1
Thai food                                    1
Greek                                        1
All                                          1
American or Italian                          1
Sub sandwhiches                              1
Wraps                                        1
Chinese cuisine (General Tso's)              1
Lean                                         1
american                                     1
Japanese                                     1
Any type of Colombian cuisine                1
Italian or Chinese                           1
Mexican cuisine                              1
Asian                                        1
mac and cheese                               1
Chinese food                                 1
italian and chinese                          1
Barbecue                                     1
lebanese or greek                            1
Authentic Chinese and Vietnamese food        1
sushi                                        1
Indian food                                  1
Nepali                                       1
I really love italian food and thai food     1
I do not like cuisine                        1
Vietnamese cuisine                           1
Mexican Food                                 1
HISPANIC CUISINE.                            1
Name: count, dtype: int64

Value counts for column 'food_childhood':
food_childhood
Pizza                                        5
Chicken                                      2
pizza                                        2
Steak                                        2
Spaghetti                                    2
                                            ..
Stromboli Mac and Cheese and Pizza           1
Isombe , Plantains and Ugali                 1
Rice and potato                              1
pizza and spaghetti                          1
rice, beans, and chicken / pizza/ tenders    1
Name: count, Length: 114, dtype: int64

Value counts for column 'healthy_meal':
healthy_meal
looks not oily                                                                                                                                            1
Grains, Veggies, (more of grains and veggies), small protein and fruit with dairy                                                                         1
usually includes natural ingredients; nonprocessed food                                                                                                   1
Fresh fruits& vegetables, organic meats                                                                                                                   1
A lean protein such as grilled chicken, green vegetables and  brown rice or other whole grain                                                             1
                                                                                                                                                         ..
mainly protein and vegetables with a complex carb                                                                                                         1
A healthy meal is a variety of food , organic food that gives you the nutrients such as protein , carbohydrates , fat , water , vitamins and minerals.    1
lots of vegetables                                                                                                                                        1
A protein, a fruit, a starch, and a salad or some sort of vegetable.                                                                                      1
a cup of rice, vegetables, and meat.                                                                                                                      1
Name: count, Length: 124, dtype: int64

Value counts for column 'ideal_diet':
ideal_diet
being healthy                                                                                                                                                         1
Try to eat 5-6 small meals a day. While trying to properly distribute carbs, protein, fruits, veggies, and dairy.                                                     1
i would say my ideal diet is my current diet                                                                                                                          1
Healthy, fresh veggies/fruits & organic foods                                                                                                                         1
Ideally I would like to be able to eat healthier foods in order to loose weight.                                                                                      1
                                                                                                                                                                     ..
My ideal diet would consist of a majority of what I consume now. I like to think I make pretty healthy choices currently, so it would most likely remain the same.    1
Eating home cooked meals everyday and being able to not eat processed foods at all.                                                                                   1
lots of veggies                                                                                                                                                       1
My ideal diet is the diet i am currently on.  The only thing i would change is a little bit less snack/junk food.                                                     1
Being able to balance between sweets, vegetables, fruits, carbohydrates, and fat.                                                                                     1
Name: count, Length: 124, dtype: int64

Value counts for column 'meals_dinner_friend':
meals_dinner_friend
Chicken, Steak, Pasta                                                2
Pasta, steak, chicken                                                1
chicken and rice with veggies, pasta, some kind of healthy recipe    1
Grilled chicken \rStuffed Shells\rHomemade Chili                     1
Chicken Parmesan, Pulled Pork, Spaghetti and meatballs               1
                                                                    ..
pasta, fish, steak                                                   1
Fried Rice \rBaked potatoes \rCurry Chicken                          1
meat, rice, kimchi                                                   1
Pizza, Spaghetti, Baked Ziti                                         1
Vegetables, Meat, and rice.                                          1
Name: count, Length: 121, dtype: int64

Value counts for column 'mother_profession':
mother_profession
Secretary                                    3
Teacher                                      3
unemployed                                   2
Banker                                       2
teacher                                      2
                                            ..
Radiological Technician                      1
Public Health Advisor                        1
Real Estate manageer                         1
Receptionist for a medical supply company    1
House-wife                                   1
Name: count, Length: 112, dtype: int64

Value counts for column 'type_sports':
type_sports
none                        8
Hockey                      7
Soccer                      4
softball                    4
soccer                      3
                           ..
I used to play softball     1
 None                       1
Tennis, Basketball          1
No, I don't play sport.     1
basketball                  1
Name: count, Length: 66, dtype: int64

In [ ]:

cuisine_mapping_numeric = {
    'Italian': 1,
    'Mexican': 2,
    'American': 3,
}

df['fav_cuisine_encoded'] = df['fav_cuisine'].map(cuisine_mapping_numeric).fillna(0)
print(df.head())

     GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0  2.400       2          1               430           NaN           315.0
1  3.654       1          1               610           3.0           420.0
2  3.300       1          1               720           4.0           420.0
3  3.200       1          1               430           3.0           420.0
4  3.500       1          1               720           2.0           420.0

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort
1       2       chocolate, chips, ice cream        Stress, bored, anger
2       2   frozen yogurt, pizza, fast food             stress, sadness
3       2  Pizza, Mac and cheese, ice cream                     Boredom
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings

   comfort_food_reasons_coded  ...  sports  thai_food  tortilla_calories  \
0                         9.0  ...     1.0          1             1165.0
1                         1.0  ...     1.0          2              725.0
2                         1.0  ...     2.0          5             1165.0
3                         2.0  ...     2.0          5              725.0
4                         1.0  ...     1.0          4              940.0

  turkey_calories  type_sports  veggies_day vitamins  waffle_calories  weight  \
0             345   car racing            5        1             1315   187.0
1             690  Basketball             4        2              900   155.0
2             500         none            5        1              900     NaN
3             690          NaN            3        1             1315     NaN
4             500     Softball            4        2              760   190.0

   fav_cuisine_encoded
0                  0.0
1                  1.0
2                  0.0
3                  0.0
4                  0.0

[5 rows x 62 columns]

In [ ]:
df['fav_cuisine_encoded']

0      0.0
1      1.0
2      0.0
3      0.0
4      0.0
      ...
120    0.0
121    0.0
122    0.0
123    1.0
124    0.0
Name: fav_cuisine_encoded, Length: 125, dtype: float64

In [ ]:
numeric_columns = []
for column in df.columns:
    if pd.api.types.is_numeric_dtype(df[column]):
        numeric_columns.append(column)
cleaned_df=df[numeric_columns]

In [ ]:
cleaned_df

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,...,soup,sports,thai_food,tortilla_calories,turkey_calories,veggies_day,vitamins,waffle_calories,weight,fav_cuisine_encoded
0,2.400,2,1,430,NaN,315.0,1,9.0,2.0,9,...,1.0,1.0,1,1165.0,345,5,1,1315,187.0,0.0
1,3.654,1,1,610,3.0,420.0,2,1.0,3.0,1,...,1.0,1.0,2,725.0,690,4,2,900,155.0,1.0
2,3.300,1,1,720,4.0,420.0,2,1.0,1.0,1,...,1.0,2.0,5,1165.0,500,5,1,900,NaN,0.0
3,3.200,1,1,430,3.0,420.0,2,2.0,2.0,2,...,1.0,2.0,5,725.0,690,3,1,1315,NaN,0.0
4,3.500,1,1,720,2.0,420.0,2,1.0,1.0,1,...,1.0,1.0,4,940.0,500,4,2,760,190.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.500,1,1,610,4.0,420.0,2,NaN,3.0,2,...,1.0,1.0,5,940.0,500,5,1,1315,156.0,0.0
121,3.000,1,1,265,2.0,315.0,2,NaN,3.0,3,...,1.0,NaN,4,940.0,500,5,2,1315,180.0,0.0
122,3.882,1,1,720,NaN,420.0,1,NaN,3.0,3,...,1.0,2.0,5,580.0,690,4,2,1315,120.0,0.0
123,3.000,2,1,720,4.0,420.0,1,NaN,3.0,7,...,2.0,2.0,1,940.0,500,3,1,1315,135.0,1.0
124,3.900,1,1,430,NaN,315.0,2,NaN,NaN,5,...,1.0,2.0,2,725.0,345,4,2,575,135.0,0.0